# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeBuild < Formula
  desc "Build (and optionally push) container images with the in-cluster buildkitd, from outside the cluster."
  homepage "https://github.com/agrospai/kube-build"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgrospAI/kube-build/releases/download/v0.0.2/kube-build_0.0.2_darwin_amd64.tar.gz"
      sha256 "821819e18da92df9648cbec0bec9a775d03d453de686c42bb6c53437ca0d6232"

      define_method(:install) do
        bin.install "kube-build"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgrospAI/kube-build/releases/download/v0.0.2/kube-build_0.0.2_darwin_arm64.tar.gz"
      sha256 "b3823238317394254d7f42e6128c9b38cf4c9aa61cd152147d7f0f7a8d76fc88"

      define_method(:install) do
        bin.install "kube-build"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgrospAI/kube-build/releases/download/v0.0.2/kube-build_0.0.2_linux_amd64.tar.gz"
      sha256 "11ccb799e893d1dc2000dcb863cf9b8ef92085447c9294a77d5eb9f01670e914"
      define_method(:install) do
        bin.install "kube-build"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgrospAI/kube-build/releases/download/v0.0.2/kube-build_0.0.2_linux_arm64.tar.gz"
      sha256 "901be88803125f32eafdabec6bdb2cf0f2cfdefd5a2b8c2056b30a084dcf2d2c"
      define_method(:install) do
        bin.install "kube-build"
      end
    end
  end

  test do
    system "#{bin}/kube-build", "--version"
  end
end
