# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeBuild < Formula
  desc "Build (and optionally push) container images with the in-cluster buildkitd, from outside the cluster."
  homepage "https://github.com/agrospai/kube-build"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgrospAI/kube-build/releases/download/v1.0.0/kube-build_1.0.0_darwin_amd64.tar.gz"
      sha256 "c98889a5018e5ce8950d93f5353d1bebf7d92143c15101a0cee31fa6d29f8dfb"

      define_method(:install) do
        bin.install "kube-build"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgrospAI/kube-build/releases/download/v1.0.0/kube-build_1.0.0_darwin_arm64.tar.gz"
      sha256 "c70d58e8a26dff0de278efdd1cd41e7e338833cd7fcb29eed9b8cc74cfedde75"

      define_method(:install) do
        bin.install "kube-build"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgrospAI/kube-build/releases/download/v1.0.0/kube-build_1.0.0_linux_amd64.tar.gz"
      sha256 "fd7e922fe71c1ffcb478750624f855dd01142b20f54dd5430706511d17836895"
      define_method(:install) do
        bin.install "kube-build"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgrospAI/kube-build/releases/download/v1.0.0/kube-build_1.0.0_linux_arm64.tar.gz"
      sha256 "fd75227abbe603b8a72fef772177b612aa7035cf457c365480646d7d956211cb"
      define_method(:install) do
        bin.install "kube-build"
      end
    end
  end

  test do
    system "#{bin}/kube-build", "--version"
  end
end
